UR	  |DESCRIPCION
316	  |DIRECCION GENERAL DE EPIDEMIOLOGIA
AYK	  |SEC TEC DEL CON NAL PARA LAS PERSONAS CON DISCAPACIDAD
NCE	  |INSTITUTO DE GERIATRIA
M7A	  |HOSPITAL REGIONAL DE ALTA ESPECIALIDAD - CHIAPAS
NBQ	  |HOSPITAL REGIONAL DE ALTA ESPECIALIDAD - BAJIO
NBR	  |HOSPITAL REGIONAL DE ALTA ESPECIALIDAD - OAXACA
NBS	  |HOSPITAL REGIONAL DE ALTA ESPECIALIDAD - YUCATAN
615	  |
NBU	  |HOSPITAL REGIONAL DE ALTA ESPECIALIDAD DE IXTAPALUCA
100	  |OFICINA DEL C. SECRETARIO
111	  |COORDINACION GENERAL DE ASUNTOS JURIDICOS Y DERECHOS HUMANOS
112	  |DIRECCION GENERAL DE COMUNICACION SOCIAL
113	  |ORGANO INTERNO DE CONTROL
114	  |UNIDAD DE ANALISIS ECONOMICO
160	  |COMISION COORDINADORA DE LOS INSTITUTOS NACIONALES DE SALUD Y HOSPITA
170	  |UNIDAD COORDINADORA DE VINCULACION Y PARTICIPACION SOCIAL
171	  |SECRETARIADO TECNICO DEL CONSEJO NACIONAL DE SALUD
172	  |DIRECCION GENERAL DE RELACIONES INTERNACIONALES
300	  |SUBSECRETARIA DE PREVENCION Y PROMOCION DE LA SALUD
310	  |DIRECCION GENERAL DE PROMOCION DE LA SALUD
312	  |SECRETARIADO TECNICO DEL CONSEJO NACIONAL CONTRA LAS ADICCIONES
313	  |SECRETARIADO TECNICO DEL CONSEJO NACIONAL DE SALUD MENTAL
314	  |SECRETARIADO TECNICO DEL CONSEJO NACIONAL PARA LAS PERSONAS CON DISCA
315	  |CENTRO NACIONAL PARA LA PREVENCION DE ACCIDENTES
416	  |UNIDAD ADMINISTRATIVA DE ENTIDADES FEDERATIVAS
500	  |SUBSECRETARIA DE ADMINISTRACION Y FINANZAS
510	  |DIRECCION GENERAL. DE PROGRAMACION, ORGANIZACION Y PRESUPUESTO
511	  |DIRECCION GENERAL DE TECNOLOGIAS DE LA INFORMACION
512	  |DIRECCION GENERAL DE RECURSOS MATERIALES Y SERVICIOS GENERALES
513	  |DIRECCION GENERAL DE RECURSOS HUMANOS
514	  |DIRECCION GENERAL DE DESARROLLO DE LA INFRAESTRUCTURA FISICA
600	  |SUBSECRETARIA DE INTEGRACION Y DESARROLLO DEL SECTOR SALUD
610	  |DIRECCION GENERAL DE CALIDAD Y EDUCACION EN SALUD
611	  |DIRECCION GENERAL DE PLANEACION Y DESARROLLO EN SALUD
613	  |DIRECCION GENERAL DE INFORMACION  EN SALUD
614       |DIRECCION GENERAL DE EVALUACION DEL DESEMPEÑO
E00	  |ADMINISTRACION DEL PATRIMONIO DE LA BENEFICIENCIA PUBLICA
H06	  |PERSONAL HOMOLOGADO
I00	  |CENTRO NACIONAL DE LA TRANSFUSION SANGUINEA
K00	  |CENTRO NACIONAL PARA LA PREVENCION Y CONTROL DEL VIH/SIDA
L00	  |CENTRO NACIONAL DE EQUIDAD DE GENERO Y SALUD REPRODUCTIVA
M00	  |COMISION NACIONAL DE ARBITRAJE MEDICO
N00	  |SERVICIOS DE ATENCION PSIQUIATRICA
O00	  |CENTRO NACIONAL DE PROGRAMAS PREVENTIVOS Y CONTOL DE ENFERMEDADES
PBP	  |PERSONAL HOMOLOGADO BENEFICIENCIA PUBLICA
PSF	  |PERSONAL HOMOLAGADO PRGRAMAS SUSTANTIVOS FEDERALES
Q00	  |CENTRO NACIONAL DE TRASPLANTES
R00	  |CENTRO NACIONAL PARA LA SALUD DE LA INFANCIA Y ADOLESCENCIA
S00	  |COMISION FEDERAL PARA LA PROTEC CONTRA RIESGOS SANITARIOS
S01	  |SERVICIOS ESTATALES DE SALUD PUBLICA EN AGUASCALIENTES
S02	  |INSTITUTO DE SERVICIOS DE SALUD PUBLICA DE BAJA CALIFORNIA
S03	  |SERVICIOS ESTATALES DE SALUD PUBLICA EN BAJA CALIFORNIA SUR
S04	  |SERVICIOS COORDINADOS DE SALUD PUBLICA EN CAMPECHE
S05	  |SERVICIOS DE SALUD DE COAHUILA
S06	  |SERVICIOS ESTATALES DE SALUD PUBLICA EN EL EDO. DE COLIMA
S07	  |SERVICIOS COORDINADOS DE SALUD PUBLICA EN CHIAPAS
S08	  |SERVICIOS COORDINADOS SE SALUD PUBLICA EN CHIHUAHUA
S09	  |SERVICIOS DE SALUD PARA LA POBLACION ABIERTA DEL D.F.
S10	  |SERVICIOS COORDINADOS DE SALUD PUBLICA EN DURANGO
S11	  |SERVICIOS ESTATALES DE SALUD PUBLICA EN GUANAJUATO
S12	  |SERVICIOS ESTATALES DE SALUD PUBLICA EN GUERRERO
S13	  |SERVICIOS COORDINADOS DE SALUD PUBLICA EN HIDALGO
S14	  |SECRETARIA DE SALUD EN EL ESTADO DE JALISCO
S15	  |SERVICIOS ESTATALES DE SALUD PUBLICA EN EL ESTADO DE MEXICO
S16	  |SERVICIOS COORDINADOS DE SALUD PUBLICA EN MICHOACAN
S17	  |SERVICIOS ESTATALES DE SALUD PUBLICA EN MORELOS
S18	  |SERVICIOS DE SALUD DE NAYARIT
S19	  |SERVICIOS ESTATALES DE SALUD PUBLICA EN NUEVO LEON
S20	  |SERVICIOS COORDINADOS DE SALUD PUBLICA EN OAXACA
S21	  |SERVICIOS COORDINADOS DE SALUD PUBLICA EN PUEBLA
S22	  |SERVICIOS ESTATALES DE SALUD PUBLICA EN QUERETARO
S23	  |SERVICIOS ESTATALES DE SALUD PUBLICA EN QUINTANA ROO
S24	  |SERVICIOS COORDINADOS DE SALUD PUBLICA EN SAN LUIS POTOSI
S25	  |SERVICIOS COORDINADOS DE SALUD PUBLICA EN SINALOA
S26	  |SERVICIOS ESTATALES DE SALUD PIBLICA EN SONORA
S27	  |SERVICIOS ESTATALES DE SALUD PUBLICA EN TABASCO
S28	  |SERVICIOS COORDINADOS DE SALUD PUBLICA EN TAMAULIPAS
S29	  |SERVICIOS ESTATALES DE SALUD PUBLICA EN TLAXCALA
S30	  |SERVICIOS COORDINADOS DE SALUD PUBLICA EN VERACRUZ
S31	  |SERVICIOS COORDINADOS DE SALUD PUBLICA EN YUCATAN
S32	  |SERVICIOS COORDINADOS DE SALUD PUBLICA EN ZACATECAS
SME	  |PERSONAL HOMOLOGADO SALUD MENTAL
SPC	  |PERSONAL DE SEGURO POPULAR COORDINACION
SPG	  |PERSONAL DE SEGURO POPULAR GASTOS CATASTROFICOS
SPM	  |PERSONAL DE SEGURO POPULAR MANDOS MEDIOS
SSP	  |PERSONAL DE SEGURO POPULAR EVENTUALES
T00	  |CENTRO NACIONAL DE EXCELENCIA TECNOLOGICA EN SALUD
U00	  |COMISION NACIONAL DE PROTECCION SOCIAL EN SALUD
V00	  |COMISION NACIONAL DE BIOETICA
VEC	  |PERSONAL HOMOLOGADO VECTORES
VGE	  |PERSONAL HOMOLOGADO VECTORES GOB. DEL ESTADO
W00	  |INSTITUTO DE GERIATRIA
180	  |COMISION NACIONAL CONTRA LAS ADICCIONES
X00	  |CENTRO NACIONAL PARA LA PREVENCION Y EL CONTROL DE LAS ADICCIONES
	  |
