OPTIONS (ERRORS=1)
LOAD DATA 
INFILE 'cuete.dat' 
APPEND
INTO TABLE "PRO_NOMINA"."TABLA"
FIELDS TERMINATED BY'|'
OPTIONALLY ENCLOSED BY '"' 
TRAILING NULLCOLS ( 
"COL1" ,
"COL2" constant 'x' ,
"COL3" 
)

